# Generated by Django 4.2.2 on 2023-06-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewnotform',
            name='phto',
        ),
        migrations.AddField(
            model_name='reviewnotform',
            name='photo',
            field=models.FileField(blank=True, upload_to='photo/'),
        ),
    ]
