# Generated by Django 4.2.2 on 2023-06-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarynotform',
            name='image',
            field=models.FileField(blank=True, upload_to='phto/'),
        ),
    ]
