# Generated by Django 4.2.2 on 2023-06-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_diarynotform_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarynotform',
            old_name='image',
            new_name='file',
        ),
    ]
