# Generated by Django 4.2.2 on 2023-06-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarynotform',
            name='image',
        ),
        migrations.AddField(
            model_name='diarynotform',
            name='file',
            field=models.FileField(blank=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='diarynotform',
            name='pub_date',
            field=models.DateTimeField(verbose_name='data published'),
        ),
    ]
