# Generated by Django 4.2.1 on 2023-06-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_alter_diarynotform_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarynotform',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
