# Generated by Django 4.2.1 on 2023-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0004_alter_diarynotform_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarynotform',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/photo/'),
        ),
    ]
