# Generated by Django 4.2.1 on 2023-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0005_diarynotform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarynotform',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
