# Generated by Django 4.2.1 on 2023-06-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("weather", models.CharField(max_length=20)),
                ("body", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="photo/")),
            ],
        ),
    ]
