# Generated by Django 4.2.2 on 2023-06-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0002_alter_journaluseform_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journaluseform',
            old_name='file',
            new_name='image',
        ),
    ]
