# Generated by Django 4.2.2 on 2023-06-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='Diarynotform',
        ),
    ]
