# Generated by Django 4.2.2 on 2023-06-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewUseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
                ('weather', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('picture', models.FileField(blank=True, upload_to='picture/')),
            ],
        ),
    ]
