# Generated by Django 4.2.1 on 2023-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewuseform',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/'),
        ),
    ]
