# Generated by Django 4.2.1 on 2023-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_alter_diarynotform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarynotform',
            name='date',
            field=models.DateTimeField(verbose_name='data published'),
        ),
    ]
