# Generated by Django 4.2.2 on 2023-06-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_alter_diarynotform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarynotform',
            name='image',
            field=models.FileField(blank=True, upload_to='phto/'),
        ),
    ]
